#!/bin/bash

if [[ $1 == "--version" ]];
then
    arm-none-eabi-gdb --version
else
    tee /tmp/arm-none-eabi-gdb.input.log | \
    arm-none-eabi-gdb \
      --init-command=`cat /tmp/cmake_current_source_dir`/.gdbinit \
      "$@" | \
    tee /tmp/arm-none-eabi-gdb.output.log
fi

